feat/element nav
multi-cell/devise-ante pull request #34
Opened 2017-11-14 04:41 UTC by maccelerated

2017-11-14 07:25 UTC, monochromicon commented
Looks like the CI build is failing. You need to add the latest version of vue-template-compiler to your dependencies. Try running the build locally and see what happens

2017-11-17 07:03 UTC, puregarlic requested changes
Overall functionality looks great, just needs some minor tweaks before we can fully accept it.

2017-11-17 07:03 UTC, monochromicon commented on src/games/Game.vue
> +    markdown: `# ROVs\n\nThe core game mechanic is driving remotely operated vehicles around a two-dimensional map.\n`
How come you're using vanilla strings with `\n` instead of template literals?

2017-11-17 07:03 UTC, monochromicon commented on src/games/Game.vue
> +  props: ['game', 'slug'],
Let's get in the habit of using the more verbose form for props. Sure, it's type checking, but there's almost no effort involved in adding it, and it's useful inline documentation. Information on the syntax can be found [here](http://devdocs.io/vue~2/api/index#props).

2017-11-17 07:03 UTC, monochromicon commented on src/games/elements/EditElement.vue
> +  props: ['markdown'],
Same comment on props here.

2017-11-17 07:03 UTC, monochromicon commented on src/games/elements/ElementNav.vue
> +    <el-dialog
Turns out there's another modal-like component that's meant for this purpose: The [Message Box](http://element.eleme.io/#/en-US/component/message-box).

2017-11-17 07:03 UTC, monochromicon commented on src/games/elements/NewElement.vue
> +  props: ['game'],
Expand this prop

2017-11-17 07:03 UTC, monochromicon commented on src/games/elements/ElementNav.vue
> +  props: ['game', 'elements'],
Expand these

2017-11-17 07:03 UTC, monochromicon commented on src/App.vue
> +    <el-menu mode="horizontal" :router="true">
Let's use the prepackaged way to do layouts in Element UI, it's basically made for the look of our application: [Container](http://element.eleme.io/#/en-US/component/container)

2017-11-17 21:31 UTC, maccelerated commented
I'll expand the props, then convert the remove-element feature to message box after that.

2017-11-28 20:58 UTC, puregarlic approved these changes
Alright, these changes look good for now. Let’s get this merged back to dev.

2017-11-28 21:21 UTC, merged